function(qf_add_client_module target_name)
    qf_add_static_library(${target_name} ${ARGN})
    target_compile_definitions(${target_name} PRIVATE QF_CLIENT_MODULE)
    target_include_directories(${target_name} PRIVATE "${PROJECT_SOURCE_DIR}/game")
    target_include_directories(${target_name} PRIVATE "${PROJECT_SOURCE_DIR}/modules")
    target_link_libraries(${target_name} PUBLIC qfengine_common)
    target_link_libraries(client_game PUBLIC ${target_name})
endfunction()

function(qf_add_server_module target_name)
    qf_add_static_library(${target_name} ${ARGN})
    target_compile_definitions(${target_name} PRIVATE QF_SERVER_MODULE)
    target_include_directories(${target_name} PRIVATE "${PROJECT_SOURCE_DIR}/game")
    target_include_directories(${target_name} PRIVATE "${PROJECT_SOURCE_DIR}/modules")
    target_link_libraries(${target_name} PUBLIC qfengine_common)
    target_link_libraries(server_game PUBLIC ${target_name})
endfunction()

function(qf_add_shared_module target_name)
    qf_add_static_library(${target_name} ${ARGN})
    target_compile_definitions(${target_name} PRIVATE QF_SHARED_MODULE)
    target_include_directories(${target_name} PRIVATE "${PROJECT_SOURCE_DIR}/game")
    target_include_directories(${target_name} PRIVATE "${PROJECT_SOURCE_DIR}/modules")
    target_link_libraries(${target_name} PUBLIC qfengine_common)
    target_link_libraries(shared_game PUBLIC ${target_name})
endfunction()
