function(qf_setup_target target_name)
    target_compile_features(${target_name} PUBLIC cxx_std_20)
    target_include_directories(${target_name} PUBLIC "${PROJECT_SOURCE_DIR}")
    
    if(WIN32)
        target_compile_definitions(${target_name} PUBLIC _CRT_SECURE_NO_WARNINGS)
        target_compile_definitions(${target_name} PUBLIC _USE_MATH_DEFINES)
        target_compile_definitions(${target_name} PUBLIC NOMINMAX)
    endif()
endfunction()

function(qf_add_executable target_name)
    add_executable(${target_name} ${ARGN})
    ##set_target_properties(${target_name} PROPERTIES WIN32_EXECUTABLE TRUE)
    ##set_target_properties(${target_name} PROPERTIES MACOSX_BUNDLE TRUE)
    qf_setup_target(${target_name})
endfunction()

function(qf_add_shared_library target_name)
    add_library(${target_name} SHARED ${ARGN})
    target_compile_definitions(${target_name} PRIVATE QF_BUILD_DLL)
    qf_setup_target(${target_name})
endfunction()

function(qf_add_static_library target_name)
    add_library(${target_name} STATIC ${ARGN})
    target_compile_definitions(${target_name} PRIVATE QF_BUILD_LIB)
    qf_setup_target(${target_name})
endfunction()
